# Generated by Django 5.0.3 on 2024-03-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='youtubeUrl',
            field=models.CharField(default='', max_length=800),
            preserve_default=False,
        ),
    ]
